name: flutter_template
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  melos: ^3.1.1
  very_good_analysis: ^5.1.0