name: template_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## Packages
  catalog:
    path: ../packages/data/catalog/
  device:
    path: ../packages/data/device/
  utility:
    path: ../packages/core/utility/
  ui:
    path: ../packages/core/ui/
  home:
    path: ../packages/features/home/

  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true